spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 282058685617-go6kd2o2jao1bhmervsia876rlggscqc.apps.googleusercontent.com

server:
  port: 8081
  servlet:
    context-path: /codebreaker-community
  error:
    include-message: always
  forward-headers-strategy: native